### ISSUE TITLE
make css better

### ISSUE THREAD

**Issue by clementroze** [codingMASTER398/noreplit.com#17]
lol yall even made the same mistake as me (no need `width: fit-content` as well as the `filter` prop)

<img width="523" alt="Screenshot 2023-10-09 at 10 11 25 PM" src="https://github.com/codingMASTER398/noreplit.com/assets/64614924/56f711b6-b422-48c4-994b-7efb4fa94192">

also at least add the `:active` state – i think it's pretty cool. Here is the code:

```css
a:active {
	top: -1px;
}
```

**Comment by clementroze** [comment]
also nice bounce effect on the cards lol ;)

**Comment by datkat21** [comment]
I'll look into making a PR for this, then there we can decide what to do. Thanks for the feedback

**Comment by clementroze** [comment]
np, gl
