### ISSUE TITLE
GitPod free not viable

### ISSUE THREAD

**Issue by markbluhm** [codingMASTER398/noreplit.com#31]
Not sure if you want to move GitPod into paid or not because it's over 200$/mo now.

Their free option only allows 50hr/mo and their paid plan is 0.36$/hr 

I'd submit a PR but IDK which way you'd want to move it and my head hurts right now. Just wanted to at least report it

**Comment by codingMASTER398** [comment]
https://github.com/codingMASTER398/noreplit.com/commit/9846a8d7a1bc0ebac851bd2ae6c780752e31e2de
